env:
  node: true
  browser: true
  es6: true
  jest: true
extends:
  - "eslint:recommended"
  - "plugin:jest/recommended"
  - "plugin:prettier/recommended"
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins: []
rules: {}
